### ISSUE TITLE
Firmware dosyası

### ISSUE THREAD

**Issue by amarettorecast** [enoymuss/h3600-root#1]
https://psaux.io/2020/03/01/Taking-Back-What-Is-Already-Yours-Router-Wars-Episode-I/

GPL kodu için ZTE'den istekte bulundum fakat yardımcı olmadılar. Modemin FCC id si de bulunmuyor sanırım. ACS üzerinden firmware dosyasını bulabilirseniz çok güzel olur.

**Comment by enoymuss** [comment]
Evimde şuanda superonline internet hattı bulunmadığı için router güncelleme almıyor o yüzden firmware dosyasını bulamadım fakat xml parametrelerinde değişiklik yaparak bulmayı deniyeceğim 1 haftalığına izmirdeyim eve döndüğümde işe koyulucam

**Comment by enoymuss** [comment]
Maalesef firmware update isteği superonline müşterisi olmadan acs serverinden almayı başaramadım aktif abonelik olduğu zaman geliyor gibi gözüküyor en güncel sürüm V9.0.0P15_TR olmasına rağmen V9.0.0P14_TR den update alamadım.
